
<field:ad1 itemname="推荐度(1-10)" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="4"  maxlength="250" page="">
</field:ad1>




<field:th itemname="套黄价" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="0"  maxlength="250" page="">
</field:th>



<field:tx itemname="通宵价" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="0"  maxlength="250" page="">
</field:tx>



<field:qt itemname="全天价" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="0"  maxlength="250" page="">
</field:qt>



<field:sm itemname="固顶通宵 " autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:sm>



<field:gc itemname="网站说明" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="请联系客服咨询价格"  maxlength="250" page="">
</field:gc>


