<field:body itemname="详细介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">
	
</field:body>
	
<field:price itemname="市场价" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="0"  maxlength="" page="">
	
</field:price>


	
<field:trueprice itemname="优惠价" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="" page="">
	
</field:trueprice>
	
<field:brand itemname="品牌" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
	
</field:brand>
	
<field:units itemname="计量单位" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
	
</field:units>
	
	
<field:vocation itemname="行业" autofield="1" notsend="0" type="stepselect" isnull="true" islist="0" default=""  maxlength="250" page="">
	
</field:vocation>
	
<field:infotype itemname="信息类型" autofield="1" notsend="0" type="stepselect" isnull="true" islist="0" default=""  maxlength="250" page="">
	
</field:infotype>
	
<field:uptime itemname="上架时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
	
</field:uptime>
	
<field:gmimg itemname="版本大图" autofield="1" notsend="0" type="textchar" isnull="true" islist="0" default="/uploads/top.gif"  maxlength="250" page="">
</field:gmimg>
<field:shuoming itemname="版本红字介绍" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default="采用最新游戏引擎:支持最新最流行的游戏功能，十分耐玩，玩家无论是打宝还是PK都有非常佳的体验，游戏技术强悍.详情请登陆游戏测试区查看！"  maxlength="250" page="">
</field:shuoming>
