
<m:item name='采集系统' link='bd_main.php' rank='' target='main' />
<m:item name='官方主页' link='http://www.dedecaiji.com' rank='' target='_blank' />
<m:item name='在线手册' link='http://www.dedecaiji.com/dedecaiji.mht' rank='' target='_blank' />
<m:item name='视频教程' link='http://www.dedecaiji.com/a/video.html' rank='' target='_blank' />
<m:item name='演示网站' link='http://www.dedecaiji.com/zz/' rank='' target='_blank' />
