<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?> <div class="aupageleft">
  

 <div class="ver_tit"><a href="/plus/guestbook.php"  target="_blank">
 <img src="/templets/yc/image/kffw.jpg"  alt="客户意见_投诉反馈" /></a></div>
 <div class="ver_tit"><a href="/tc/index.html"  target="_blank">
 <img src="/templets/yc/image/jiaff_img_lc1.gif"  alt="套餐订制·制作流程一" align="absmiddle" /></a>&nbsp;<a href="/tc/index.html"  target="_blank"><img src="/templets/yc/image/jiaff_img_lc2.gif"  alt="套餐订制·制作流程二" align="absmiddle" /></a></div>
 <div class="ver_tit"><a href="/tc/index.html"  target="_blank">
 <img src="/templets/yc/image/jiaff_img_lc3.gif"  alt="套餐订制·制作流程三" /></a></div>
 <div class="ver_tit"><a href="/tc/index.html"  target="_blank">
 <img src="/templets/yc/image/jiaff_img_lc4.gif"  alt="套餐订制·制作流程四" /></a></div>
  <br/><br/>
 <?php include $this->CompilerInclude("qq.htm");
 ?>
 <div class="yxcsqsj_cen">
 <a href="/Comm/GameTesting/index.html" target="_blank"> <img width="210" height="116" src="/templets/yc/image/yxcsqsj.gif" border="0"></a>
</div>
 </div>